title: ["Devaneios"]
description: ["Local onde utilizo para colocar meus artigos, textos e post que escrevo."]
show_downloads: ["true"]
google_analytics: [1234]

baseurl: "/devaneios"

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
